check KF5I18n minimum version To prevent compiling issue:
Consolidate compiler generated dependencies of target heaptrack_gui
[ 80%] Building CXX object src/analyze/gui/CMakeFiles/heaptrack_gui.dir/mainwindow.cpp.o
/home/tw/Documents/GitHub/heaptrack/src/analyze/gui/mainwindow.cpp:14:10: fatal error: KLazyLocalizedString: No such file or directory
   14 | #include <KLazyLocalizedString>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/analyze/gui/CMakeFiles/heaptrack_gui.dir/build.make:115: src/analyze/gui/CMakeFiles/heaptrack_gui.dir/mainwindow.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1225: src/analyze/gui/CMakeFiles/heaptrack_gui.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

It's because the include KLazyLocalizedString is not available in older version:

https://api.kde.org/frameworks/ki18n/html/classKLazyLocalizedString.html